/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import com.google.gson.Gson;
import com.google.gson.stream.JsonReader;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.Reader;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;

public class App {

    public static void main(String[] args) throws FileNotFoundException {
        //jsonBasics();
        Gson gson = new Gson();
//        File jsonFile = new File("app/src/main/resources/Contact.json");
        Reader reader = new FileReader("app/src/main/resources/Contact.json");
        Contact convertedObject = gson.fromJson(reader, Contact.class);
        System.out.println(convertedObject);
    }

    private static void jsonBasics() {
        Gson gson = new Gson();
        int[] numbers = {1,2,3,4,5};
        String[] letters = {"a", "b", "c", "d"};

        String arrayJson = gson.toJson(letters);

        System.out.println(Arrays.toString(gson.fromJson(arrayJson,String[].class)));

        JsonTest jsonTest = new JsonTest();
        String jsonValue = gson.toJson(jsonTest);

        System.out.println(jsonValue);

        JsonTest testObject = gson.fromJson(jsonValue, JsonTest.class);

        System.out.println(testObject.name);
        System.out.println(testObject.age);
        System.out.println(testObject.isStudent);
    }
}

class JsonTest{
    String name = "Aya";
    int age = 25;
    boolean isStudent = true;
    JsonTest(){

    }
}