/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testLibrary;

import org.junit.Test;

import java.util.ArrayList;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test
    public void testReverseArray(){
        ArrayList<String> testArray = new ArrayList<>();
        testArray.add("5");
        testArray.add("4");
        testArray.add("3");
        testArray.add("2");

        Library classUnderTest = new Library();
        ArrayList<String> reversed = classUnderTest.reverseArray(testArray);

        assertEquals("The first item is equal to 2","2",reversed.get(0));
        assertEquals("The second item is equal to 3","3",reversed.get(1));
        assertEquals("The first item is equal to 4","4",reversed.get(2));
        assertEquals("The first item is equal to 5","5",reversed.get(3));
        assertEquals("Both sizes are the same", reversed.size(),testArray.size());


    }
}
