/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testLibrary;

import java.util.ArrayList;

public class Library {
    public boolean someLibraryMethod(){
    return true;
    }
    public ArrayList reverseArray(ArrayList<String> names){
        ArrayList<String> reversed = new ArrayList<>();

        for(int i = names.size()-1 ; i >= 0 ; i--){
            reversed.add(names.get(i));
        }
        return reversed;
    }
}
