/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oop;

import garden.Plant;

public class App {


    public static void main(String[] args) {

        Rose rose = new Rose("white rose","white",2);

        System.out.println(rose.getName() + "'s color is "+ rose.getColor() + " and it's height is "+rose.getHeight() + " and it has "+ rose
                .getThorns() + " thorns");

        rose.grow();
        System.out.println(rose.getName() + "'s color is "+ rose.getColor() + " and it's height is "+rose.getHeight() + " and it has "+ rose
                .getThorns() + " thorns");

        System.out.println("The rose "+rose);
        Flower.chop(rose);


        // recursion functions ..
        pyramid(5);
        upsideDownPyramid(5);
    }


    public static void pyramid(int rows){
        if(rows > 0) {
            pyramid(rows - 1);
            starsRow(rows);
        }
    }

    public static void upsideDownPyramid(int rows){
        if(rows > 0) {
            starsRow(rows);
            upsideDownPyramid(rows-1);
        }
    }

    public static void starsRow(int n){
        for(int j = 0; j < n;j++) {
            System.out.print("*");
        }
        System.out.println();
    }
}
