/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedList;

public class App {

    public static void main(String[] args) {
        LinkedList myLinkedList = new LinkedList();
        System.out.println(myLinkedList);
        myLinkedList.insert("test 1");
        System.out.println(myLinkedList);
        myLinkedList.insert(5);
        System.out.println(myLinkedList);
    }
}
