/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oop;

import java.util.ArrayList;

public class App {

    public static void main(String[] args) {

//        Rose rose = new Rose("My First Rose", 5,"red");
//        System.out.println(rose);
//        rose.grow();
//        rose.grow();
//        rose.grow();
//        System.out.println(rose);
//
//        Tulip tulip = new Tulip("first tulip",2,"pink");
//        System.out.println(tulip);
//        tulip.grow();
//        tulip.grow();
//        tulip.grow();
//        System.out.println(tulip);

        // inheritance (extends) -> is-a     Rosa is-a Flower , Tulip is-a Flower

        Garden garden = new Garden();
        garden.plant();
//        Flower roseFlower = new Rose("rose flower",5,"black");
//        Flower tulipFlower = new Tulip("tulip flower", 2,"white");
//
//
//        System.out.println(roseFlower);
//        System.out.println(tulipFlower);
//
//        roseFlower.grow();
//        tulipFlower.grow();
//
//        roseFlower.grow();
//        tulipFlower.grow();
//
//        roseFlower.grow();
//        tulipFlower.grow();
//
//        System.out.println(roseFlower);
//        System.out.println(tulipFlower);




    }
}
